### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by mcasperson** [OctopusSamples/content-team-apps#13]
This issue has been created to collect general feedback and suggestions for the Octopus Workflow Builder. Leave a comment to let us know how we did.

* Was this tool useful?
* Did you encounter any bugs?
* Would you recommend this tool to your colleagues?
* Did the sample projects help demonstrate how modern CI/CD pipelines should work?
* Do you have an idea for a feature?

**Comment by rpresser** [comment]
Your decision to support AWS made it impossible for us to even inspect this tool.

**Comment by mcasperson** [comment]
@rpresser The tool itself is designed to be mostly cloud agnostic, as it simply collects inputs and then generates templates via Yeoman. The templates are fairly complex though, which is why this initial release only targets a single cloud provider.

If you have a preferred cloud provider though, that would be useful feedback as we decide which scenarios to tackle in future.

**Comment by rpresser** [comment]
We use Azure for some things, and an on-prem K8S for others.  Thanks.
