### ISSUE TITLE
Deploy EKS Cluster succeeded with errors

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusSamples/content-team-apps#14]
Initial setup process using the App Builder tool went off without a hitch but the `Deploy EKS Cluster` project succeeded with a few errors.

Screenshot for quick reference:
![image](https://user-images.githubusercontent.com/18252832/161878149-dd603f89-6409-4627-bbf6-baa31ad12a7e.png)

Raw Logs:
[ServerTasks-252185.log.txt](https://github.com/OctopusSamples/content-team-apps/files/8422855/ServerTasks-252185.log.txt)

GitHub Actions Logs:
[GitHub Actions - EKS Deployment.txt](https://github.com/OctopusSamples/content-team-apps/files/8423404/GitHub.Actions.-.EKS.Deployment.txt)

**Comment by mcasperson** [comment]
The issue in this log are the following lines:

```
unable to recognize "/build/v2_4_1_full.yaml": no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1"
00:57:41   Error    |       Error from server (InternalError): error when creating "/build/v2_4_1_full.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
00:57:41   Error    |       Error from server (InternalError): error when creating "/build/v2_4_1_full.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
```

**Comment by mcasperson** [comment]
Given the CRDs are created by the file `v2_4_1_full.yaml`, I think what is happening here is that the CRDs are not ready by the time the other resources in the file are being deployed.

For example, https://stackoverflow.com/questions/57115602/how-to-kubectl-wait-for-crd-creation describes how to wait for CRDs to be established, indicating there is a lag time during their initialization.

**Comment by mcasperson** [comment]
Looking at the GitHub Actions logs, the deployment of the EKS cluster timed out, meaning other steps like building Docker images never ran, and so any manual deployment of the image to Kubernetes could not find an image to use.

I think the solution here is to increase the timeout for the EKS cluster deployment from 10 mins.

**Comment by mcasperson** [comment]
The timeout will be addressed with this change:

![image](https://user-images.githubusercontent.com/160104/161894935-2757ec27-84d2-4acc-a2b8-76a403b5186d.png)

**Comment by mcasperson** [comment]
With further testing I can confirm creating EKS clusters can take upwards of 15 minutes, so a better solution is to trigger the deployment that creates the cluster but not wait for the deployment to finish.

The issues setting up the ALB ingress controller appear to be resolved by first deploying the CRDs, waiting for them to be in an established state, and then proceeding with the remaining resources.

These fixes have been pushed to the dev instance.
